services:
  dev-db:
    image: postgres:15
    environment:
      POSTGRES_DB: appointments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5437:5432
    networks:
      - hospital_network

networks:
  hospital_network: