// Mock data for doctor portal
export const mockDoctor = {
  id: 1,
  userId: 1,
  firstName: "Dr. Aisha",
  lastName: "Khan",
  email: "dr.aisha@hospital.com",
  specialization: "General Practitioner",
  experience: 8,
  qualification: "MBBS, MD",
  department: "General Medicine",
  licenseNumber: "LIC-2015-00123",
};

export const mockPatients = [
  {
    id: 1,
    firstName: "Ahmed",
    lastName: "Hassan",
    email: "ahmed@email.com",
    dateOfBirth: "1990-05-15",
    bloodGroup: "O+",
    phoneNumber: "03001234567",
    medicalHistory: "Hypertension, controlled with medication",
  },
  {
    id: 2,
    firstName: "Fatima",
    lastName: "Ali",
    email: "fatima@email.com",
    dateOfBirth: "1995-08-20",
    bloodGroup: "A+",
    phoneNumber: "03009876543",
    medicalHistory: "Type 2 Diabetes",
  },
  {
    id: 3,
    firstName: "Hassan",
    lastName: "Malik",
    email: "hassan@email.com",
    dateOfBirth: "1988-03-10",
    bloodGroup: "B+",
    phoneNumber: "03005555555",
    medicalHistory: "Asthma, well-controlled",
  },
  {
    id: 4,
    firstName: "Zainab",
    lastName: "Ahmed",
    email: "zainab@email.com",
    dateOfBirth: "1992-11-25",
    bloodGroup: "AB+",
    phoneNumber: "03007777777",
    medicalHistory: "Thyroid disorder",
  },
];

export const mockDrugs = [
  { id: 1, name: "Aspirin", strength: "500mg", dosageForm: "Tablet", formulaName: "Acetylsalicylic Acid" },
  { id: 2, name: "Amoxicillin", strength: "250mg", dosageForm: "Capsule", formulaName: "Amoxicillin Trihydrate" },
  { id: 3, name: "Ibuprofen", strength: "400mg", dosageForm: "Tablet", formulaName: "Ibuprofen" },
  { id: 4, name: "Metformin", strength: "500mg", dosageForm: "Tablet", formulaName: "Metformin Hydrochloride" },
  { id: 5, name: "Lisinopril", strength: "10mg", dosageForm: "Tablet", formulaName: "Lisinopril" },
  { id: 6, name: "Atorvastatin", strength: "20mg", dosageForm: "Tablet", formulaName: "Atorvastatin Calcium" },
  { id: 7, name: "Omeprazole", strength: "20mg", dosageForm: "Capsule", formulaName: "Omeprazole" },
  { id: 8, name: "Vitamin D3", strength: "1000IU", dosageForm: "Softgel", formulaName: "Cholecalciferol" },
];

export const mockLabTests = [
  { id: 1, name: "Complete Blood Count (CBC)" },
  { id: 2, name: "Liver Function Tests (LFT)" },
  { id: 3, name: "Kidney Function Tests (KFT)" },
  { id: 4, name: "Fasting Blood Sugar" },
  { id: 5, name: "Thyroid Profile (TSH, T3, T4)" },
  { id: 6, name: "Lipid Profile" },
  { id: 7, name: "Urinalysis" },
  { id: 8, name: "ECG" },
];

export const mockSchedules = [
  {
    id: 1,
    doctorId: 1,
    from: new Date("2024-12-18T09:00:00.000Z"),
    to: new Date("2024-12-18T12:00:00.000Z"),
    noOfSlots: 6,
  },
  {
    id: 2,
    doctorId: 1,
    from: new Date("2024-12-19T14:00:00.000Z"),
    to: new Date("2024-12-19T17:00:00.000Z"),
    noOfSlots: 6,
  },
];

export const mockAppointmentSlots = [
  { id: 1, scheduleId: 1, startTime: new Date("2024-12-18T09:00:00.000Z"), endTime: new Date("2024-12-18T09:30:00.000Z"), isBookable: true, isBooked: true },
  { id: 2, scheduleId: 1, startTime: new Date("2024-12-18T09:30:00.000Z"), endTime: new Date("2024-12-18T10:00:00.000Z"), isBookable: true, isBooked: true },
  { id: 3, scheduleId: 1, startTime: new Date("2024-12-18T10:00:00.000Z"), endTime: new Date("2024-12-18T10:30:00.000Z"), isBookable: true, isBooked: false },
  { id: 4, scheduleId: 1, startTime: new Date("2024-12-18T10:30:00.000Z"), endTime: new Date("2024-12-18T11:00:00.000Z"), isBookable: false, isBooked: false },
  { id: 5, scheduleId: 2, startTime: new Date("2024-12-19T14:00:00.000Z"), endTime: new Date("2024-12-19T14:30:00.000Z"), isBookable: true, isBooked: true },
  { id: 6, scheduleId: 2, startTime: new Date("2024-12-19T14:30:00.000Z"), endTime: new Date("2024-12-19T15:00:00.000Z"), isBookable: true, isBooked: false },
];

export const mockBookedAppointments = [
  {
    id: 1,
    patientId: 1,
    slotId: 1,
    scheduleId: 1,
    startTime: "2024-12-18T09:00:00.000Z",
    endTime: "2024-12-18T09:30:00.000Z",
    reason: "Regular checkup",
    status: "scheduled",
    patient: {
      firstName: "Ahmed",
      lastName: "Hassan",
      dateOfBirth: "1990-05-15",
      bloodGroup: "O+",
      medicalHistory: "Hypertension, controlled with medication",
      allergies: "None",
    },
    createdAt: "2024-12-10T08:00:00.000Z",
  },
  {
    id: 2,
    patientId: 2,
    slotId: 2,
    scheduleId: 1,
    startTime: "2024-12-18T09:30:00.000Z",
    endTime: "2024-12-18T10:00:00.000Z",
    reason: "Diabetes follow-up",
    status: "scheduled",
    patient: {
      firstName: "Fatima",
      lastName: "Ali",
      dateOfBirth: "1995-08-20",
      bloodGroup: "A+",
      medicalHistory: "Type 2 Diabetes",
      allergies: "Penicillin",
    },
    createdAt: "2024-12-10T09:00:00.000Z",
  },
  {
    id: 3,
    patientId: 3,
    slotId: 5,
    scheduleId: 2,
    startTime: "2024-12-19T14:00:00.000Z",
    endTime: "2024-12-19T14:30:00.000Z",
    reason: "Asthma consultation",
    status: "scheduled",
    patient: {
      firstName: "Hassan",
      lastName: "Malik",
      dateOfBirth: "1988-03-10",
      bloodGroup: "B+",
      medicalHistory: "Asthma, well-controlled",
      allergies: "Dust, pollen",
    },
    createdAt: "2024-12-11T10:00:00.000Z",
  },
  {
    id: 4,
    patientId: 4,
    slotId: 6,
    scheduleId: 2,
    startTime: "2024-12-19T14:30:00.000Z",
    endTime: "2024-12-19T15:00:00.000Z",
    reason: "Thyroid consultation",
    status: "scheduled",
    patient: {
      firstName: "Zainab",
      lastName: "Ahmed",
      dateOfBirth: "1992-11-25",
      bloodGroup: "AB+",
      medicalHistory: "Thyroid disorder",
      allergies: "None",
    },
    createdAt: "2024-12-12T11:00:00.000Z",
  },
];

export const mockCheckups = [
  {
    id: 1,
    appointmentId: 1,
    appointment: {
      id: 1,
      patientId: 1,
      slotId: 1,
      reason: "Regular checkup",
      createdAt: "2024-12-10T08:00:00.000Z",
      slot: {
        startTime: "2024-12-10T09:00:00.000Z",
        endTime: "2024-12-10T09:30:00.000Z",
      },
      patient: {
        id: 1,
        firstName: "Ahmed",
        lastName: "Hassan",
        dateOfBirth: "1990-05-15T00:00:00.000Z",
        bloodGroup: "O+",
        medicalHistory: "Hypertension, controlled with medication",
        allergies: "None",
      },
    },
    bloodPressure: "120/80",
    temperature: "98.6",
    heartRate: "72",
    bloodSugar: "110",
    symptoms: "Mild headache, fatigue for the past 2 days. Patient reports stress at work.",
    diagnosis: "Tension headache. Likely stress-induced. No signs of serious underlying condition.",
    notes: "Patient advised to maintain healthy lifestyle, manage stress, ensure adequate hydration and rest. Monitor symptoms. Return if worsening or persistent beyond 5 days.",
    prescription: {
      id: 1,
      additionalMedications: null,
      medications: [
        {
          id: 1,
          drugId: 1,
          drug: {
            id: 1,
            name: "Aspirin",
            strength: "500mg",
            dosageForm: "Tablet",
            formulaName: "Acetylsalicylic Acid",
          },
          dosePerIntake: "500mg",
          timesPerDay: 2,
          totalDays: 3,
          instructions: "Take after meals with plenty of water",
        },
      ],
    },
    checkupTestRecommendation: {
      id: 1,
      additionalTests: null,
      recommendedLabTests: [
        {
          id: 1,
          labTest: {
            id: 4,
            name: "Fasting Blood Sugar",
          },
        },
      ],
    },
    createdAt: "2024-12-10T09:45:00.000Z",
    updatedAt: "2024-12-10T09:45:00.000Z",
  },
  {
    id: 2,
    appointmentId: 2,
    appointment: {
      id: 2,
      patientId: 2,
      slotId: 2,
      reason: "Diabetes follow-up",
      createdAt: "2024-12-05T08:00:00.000Z",
      slot: {
        startTime: "2024-12-05T10:00:00.000Z",
        endTime: "2024-12-05T10:30:00.000Z",
      },
      patient: {
        id: 2,
        firstName: "Fatima",
        lastName: "Ali",
        dateOfBirth: "1995-08-20T00:00:00.000Z",
        bloodGroup: "A+",
        medicalHistory: "Type 2 Diabetes diagnosed 2 years ago",
        allergies: "Penicillin",
      },
    },
    bloodPressure: "125/85",
    temperature: "98.4",
    heartRate: "75",
    bloodSugar: "145",
    symptoms: "Increased thirst, frequent urination, occasional dizziness. Reports inconsistent medication adherence.",
    diagnosis: "Type 2 Diabetes - slightly elevated glucose levels. Poor glycemic control due to medication non-compliance.",
    notes: "Patient counseled extensively on importance of medication adherence, dietary modifications (reduce refined carbs, increase fiber), and regular physical activity (30 min daily walking). Emphasized monitoring blood sugar levels. Follow-up in 2 weeks to reassess. Consider adjustment if no improvement.",
    prescription: {
      id: 2,
      additionalMedications: "Patient should continue with current Lisinopril 10mg (1x daily) for blood pressure management",
      medications: [
        {
          id: 2,
          drugId: 4,
          drug: {
            id: 4,
            name: "Metformin",
            strength: "500mg",
            dosageForm: "Tablet",
            formulaName: "Metformin Hydrochloride",
          },
          dosePerIntake: "500mg",
          timesPerDay: 3,
          totalDays: 30,
          instructions: "Take with meals to reduce GI upset. Do not skip doses.",
        },
        {
          id: 3,
          drugId: 8,
          drug: {
            id: 8,
            name: "Vitamin D3",
            strength: "1000IU",
            dosageForm: "Softgel",
            formulaName: "Cholecalciferol",
          },
          dosePerIntake: "1000IU",
          timesPerDay: 1,
          totalDays: 30,
          instructions: "Take in the morning with breakfast",
        },
      ],
    },
    checkupTestRecommendation: {
      id: 2,
      additionalTests: "HbA1c (Glycated Hemoglobin) - to assess 3-month average blood sugar control",
      recommendedLabTests: [
        {
          id: 2,
          labTest: {
            id: 6,
            name: "Lipid Profile",
          },
        },
        {
          id: 3,
          labTest: {
            id: 3,
            name: "Kidney Function Tests (KFT)",
          },
        },
      ],
    },
    createdAt: "2024-12-05T10:35:00.000Z",
    updatedAt: "2024-12-05T10:35:00.000Z",
  },
  {
    id: 3,
    appointmentId: 3,
    appointment: {
      id: 3,
      patientId: 3,
      slotId: 5,
      reason: "Asthma consultation",
      createdAt: "2024-11-28T08:00:00.000Z",
      slot: {
        startTime: "2024-11-28T14:00:00.000Z",
        endTime: "2024-11-28T14:30:00.000Z",
      },
      patient: {
        id: 3,
        firstName: "Hassan",
        lastName: "Malik",
        dateOfBirth: "1988-03-10T00:00:00.000Z",
        bloodGroup: "B+",
        medicalHistory: "Asthma since childhood, well-controlled with inhalers",
        allergies: "Dust, pollen, pet dander",
      },
    },
    bloodPressure: "118/76",
    temperature: "98.2",
    heartRate: "70",
    bloodSugar: "95",
    symptoms: "Shortness of breath, wheezing at night, chest tightness. Triggered by recent exposure to dust during home renovation.",
    diagnosis: "Acute asthma exacerbation due to environmental allergen exposure. Lung function slightly reduced but responding to bronchodilator.",
    notes: "Patient advised to avoid dust exposure, use air purifiers, keep inhaler accessible at all times. Demonstrated proper inhaler technique. If symptoms worsen or no improvement in 3 days, visit ER. Follow-up in 1 week.",
    prescription: {
      id: 3,
      additionalMedications: "Continue current maintenance inhaler (Fluticasone/Salmeterol 250/25mcg, 2 puffs twice daily)",
      medications: [
        {
          id: 4,
          drugId: 2,
          drug: {
            id: 2,
            name: "Amoxicillin",
            strength: "250mg",
            dosageForm: "Capsule",
            formulaName: "Amoxicillin Trihydrate",
          },
          dosePerIntake: "250mg",
          timesPerDay: 3,
          totalDays: 7,
          instructions: "Take with or without food. Complete full course even if feeling better.",
        },
      ],
    },
    checkupTestRecommendation: {
      id: 3,
      additionalTests: "Spirometry (if symptoms persist after 1 week) - to assess lung function",
      recommendedLabTests: [
        {
          id: 4,
          labTest: {
            id: 1,
            name: "Complete Blood Count (CBC)",
          },
        },
      ],
    },
    createdAt: "2024-11-28T14:40:00.000Z",
    updatedAt: "2024-11-28T14:40:00.000Z",
  },
];